version: '3.7'

services:
  # App backend service
  app-server:
    image: image-sharing:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE: db
      DATABASE_USER: app
      DATABASE_PASSWORD: app123
      S3_BUCKET: bucket_name
    networks:
      - backend

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: